### ISSUE TITLE
Unhandled Messages: don't throw errors?

### ISSUE THREAD

**Issue by jelling** [StableCanvas/comfyui-client#4]
Unless I'm missing it, there is no way to register custom event messages. But `ComfyUIWsClient` throws exceptions when it encounters unknown messages such as the one below.

So ideally it should either a) not throw these errors, b) make throwing them configurable, or c) allow custom messages to be registered.

```
Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 8.3, "ram_total": 540647596032, "ram_used": 82293686272, "ram_used_percent": 15.9, "hdd_total": 10737418240, "hdd_used": 84619264, "hdd_used_percent": 0.8, "device_type": "cuda", "gpus": [{"gpu_utilization": 0, "gpu_temperature": 33, "vram_total": 25757220864, "vram_used": 7877689344, "vram_used_percent": 30.58439179286761}]}} Error: Unknown message type crystools.monitor
    at WebSocket.<anonymous> (/Users/jelling/dev/rbt/rbt-nx/comfyui-client/src/ComfyUIWsClient.ts:401:23)
    at callListener (/Users/jelling/dev/rbt/rbt-nx/comfyui-client/examples/nodejs/node_modules/.pnpm/ws@8.16.0/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/Users/jelling/dev/rbt/rbt-nx/comfyui-client/examples/nodejs/node_modules/.pnpm/ws@8.16.0/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:517:28)
    at WebSocket.emit (node:domain:489:12)
    at Receiver.receiverOnMessage (/Users/jelling/dev/rbt/rbt-nx/comfyui-client/examples/nodejs/node_modules/.pnpm/ws@8.16.0/node_modules/ws/lib/websocket.js:1209:20)
    at Receiver.emit (node:events:517:28)
    at Receiver.emit (node:domain:489:12)
    at Receiver.dataMessage (/Users/jelling/dev/rbt/rbt-nx/comfyui-client/examples/nodejs/node_modules/.pnpm/ws@8.16.0/node_modules/ws/lib/receiver.js:603:14)
    at /Users/jelling/dev/rbt/rbt-nx/comfyui-client/examples/nodejs/node_modules/.pnpm/ws@8.16.0/node_modules/ws/lib/receiver.js:534:12
```

**Comment by zhzLuke96** [comment]
thx feedback.

added ef1e08dba3575afbe15e40bed1510520c829a8c5

Custom event registration is now supported. You can find details in `Custom Events` in [README](https://github.com/StableCanvas/comfyui-client?tab=readme-ov-file#custom-events)
